.TH q "1" "Jun 2005" "Gentoo" "User Commands"
.SH NAME
q \- manual page for q, qfile, quse, qsearch, qlist
.SH SYNOPSIS
.B 
\fIq\fR \fR<function> [arguments]\fR
.TP
or: \fB\<function> [arguments]\fR
.SH DESCRIPTION
* Dump portage info on stuff
.SH FUNCTIONS
\fB\q\fR, \fB\<function> <args>\fR 
 - qfile <filename>   : list all pkgs owning files
 - qlist <pkgname>    : list files owned by pkgname
 - qsearch <regex>    : search pkgname/desc
 - quse <useflag>     : find pkgs using useflag
 - qsize <pkgname>    : calculate size usage
 - qcheck <pkgname>   : verify mtimes/digests
 - qdepends <pkgname> : show dependency info
.SH "COMMON OPTIONS"
.TP
\fB-C\fR, \fB\-\-nocolor\fR
* Don't output color
.TP
\fB\-h\fR, \fB\-\-help\fR
* Print this help and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
* Print version and exit
.SH "AUTHORS"
.nf
Ned Ludd <solar@gentoo.org>
Mike Frysinger <vapier@gentoo.org>
.fi
.SH "REPORTING BUGS"
Please report bugs via http://bugs.gentoo.org/
.SH "SEE ALSO"
.BR portage (5)
.SH "CVS HEADER"
$Header: /var/cvsroot/gentoo-projects/portage-utils/man/q.1,v 1.2 2005/06/16 23:52:20 vapier Exp $
