.TH qcache "1" "Mar 2014" "Gentoo Foundation" "qcache"
.SH NAME
qcache \- search the metadata cache
.SH SYNOPSIS
.B qcache
\fI<opts> <action> <args>\fR
.SH DESCRIPTION

.SH OPTIONS
.TP
\fB\-p\fR \fI<arg>\fR, \fB\-\-matchpkg\fR \fI<arg>\fR
match pkgname
.TP
\fB\-c\fR \fI<arg>\fR, \fB\-\-matchcat\fR \fI<arg>\fR
match catname
.TP
\fB\-i\fR, \fB\-\-imlate\fR
list packages that can be marked stable on a given arch
.TP
\fB\-d\fR, \fB\-\-dropped\fR
list packages that have dropped keywords on a version bump on a given arch
.TP
\fB\-t\fR, \fB\-\-testing\fR
list packages that have ~arch versions, but no stable versions on a given arch
.TP
\fB\-s\fR, \fB\-\-stats\fR
display statistics about the portage tree
.TP
\fB\-a\fR, \fB\-\-all\fR
list packages that have at least one version keyworded for on a given arch
.TP
\fB\-n\fR, \fB\-\-not\fR
list packages that aren't keyworded on a given arch.
.TP
\fB\-\-root\fR \fI<arg>\fR
Set the ROOT env var
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Make a lot of noise
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Tighter output; suppress warnings
.TP
\fB\-C\fR, \fB\-\-nocolor\fR
Don't output color
.TP
\fB\-h\fR, \fB\-\-help\fR
Print this help and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version and exit

.SH "REPORTING BUGS"
Please report bugs via http://bugs.gentoo.org/
.br
Product: Portage Development; Component: Tools
.SH AUTHORS
.nf
Ned Ludd <solar@gentoo.org>
Mike Frysinger <vapier@gentoo.org>
.fi
.SH "SEE ALSO"
.BR q (1),
.BR qatom (1),
.BR qcheck (1),
.BR qdepends (1),
.BR qfile (1),
.BR qgrep (1),
.BR qlist (1),
.BR qlop (1),
.BR qmerge (1),
.BR qpkg (1),
.BR qsearch (1),
.BR qsize (1),
.BR qtbz2 (1),
.BR quse (1),
.BR qxpak (1)
