.TH qdepends "1" "Sep 2013" "Gentoo Foundation" "qdepends"
.SH NAME
qdepends \- show dependency info
.SH SYNOPSIS
.B qdepends
\fI<opts> <pkgname>\fR
.SH DESCRIPTION
The qdepends applet has a couple different modes.  Normally it is geared towards
answering the queries "what does package X depend on" and "what packages depend
on X".  Both can further be classified into build, run, and post dependencies.

By default, it will tell you the build time dependencies only (DEPEND).

Currently, qdepends will only query installed packages.  There is no support for
querying packages not yet installed (the \fBequery\fR(1) tool can do that).
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-depend\fR
Show DEPEND info (default)
.TP
\fB\-r\fR, \fB\-\-rdepend\fR
Show RDEPEND info
.TP
\fB\-p\fR, \fB\-\-pdepend\fR
Show PDEPEND info
.TP
\fB\-k\fR \fI<arg>\fR, \fB\-\-key\fR \fI<arg>\fR
User defined vdb key
.TP
\fB\-Q\fR \fI<arg>\fR, \fB\-\-query\fR \fI<arg>\fR
Query reverse deps
.TP
\fB\-N\fR, \fB\-\-name\-only\fR
Only show package name
.TP
\fB\-a\fR, \fB\-\-all\fR
Show all DEPEND info
.TP
\fB\-f\fR, \fB\-\-format\fR
Pretty format specified depend strings
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Make a lot of noise
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Tighter output; suppress warnings
.TP
\fB\-C\fR, \fB\-\-nocolor\fR
Don't output color
.TP
\fB\-h\fR, \fB\-\-help\fR
Print this help and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version and exit
.SH "EXAMPLES"
For finding out what a particular package depends on for building, you could do:
.nf
	$ \fIqdepends nano\fR
	app-editors/nano-2.3.2: >=sys-libs/ncurses-5.9-r1[unicode] sys-apps/file ...
.fi
This tells us that we have \fIapp-editors/nano-2.3.2\fR installed and it depends
on ncurses (among other things).
.SH "REPORTING BUGS"
Please report bugs via http://bugs.gentoo.org/
.br
Product: Portage Development; Component: Tools
.SH AUTHORS
.nf
Ned Ludd <solar@gentoo.org>
Mike Frysinger <vapier@gentoo.org>
.fi
.SH "SEE ALSO"

