.TH qmerge "1" "January 2007" "Gentoo Foundation" "qmerge"
.SH NAME
qmerge \- fetch and merge binary package
.SH SYNOPSIS
.B qmerge
\fI<pkgnames>\fR
.SH DESCRIPTION
Options: \fB\-[fFsKUpuyO5vqChV]\fR
.TP
\fB\-f\fR, \fB\-\-fetch\fR
* Fetch package and newest Packages metadata
.TP
\fB\-F\fR, \fB\-\-force\fR
* Fetch package (skipping Packages)
.TP
\fB\-s\fR, \fB\-\-search\fR
* Search available packages
.TP
\fB\-K\fR, \fB\-\-install\fR
* Install package
.TP
\fB\-U\fR, \fB\-\-unmerge\fR
* Uninstall package
.TP
\fB\-p\fR, \fB\-\-pretend\fR
* Pretend only
.TP
\fB\-u\fR, \fB\-\-update\fR
* Update only
.TP
\fB\-y\fR, \fB\-\-yes\fR
* Don't prompt before overwriting
.TP
\fB\-O\fR, \fB\-\-nodeps\fR
* Don't merge dependencies
.TP
\fB\-5\fR, \fB\-\-nomd5\fR
* Don't verify MD5 digest of files
.TP
\fB\-v\fR, \fB\-\-verbose\fR
* Make a lot of noise
.TP
\fB\-q\fR, \fB\-\-quiet\fR
* Tighter output; suppress warnings
.TP
\fB\-C\fR, \fB\-\-nocolor\fR
* Don't output color
.TP
\fB\-h\fR, \fB\-\-help\fR
* Print this help and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
* Print version and exit
.PP
$Id: qmerge.1,v 1.13 2007/01/07 20:32:41 solar Exp $
