.TH quse "1" "Mar 2014" "Gentoo Foundation" "quse"
.SH NAME
quse \- find pkgs using useflags
.SH SYNOPSIS
.B quse
\fI<opts> <useflag>\fR
.SH DESCRIPTION

.SH OPTIONS
.TP
\fB\-e\fR, \fB\-\-exact\fR
Show exact non regexp matching using strcmp
.TP
\fB\-a\fR, \fB\-\-all\fR
Show annoying things in IUSE
.TP
\fB\-K\fR, \fB\-\-keywords\fR
Use the KEYWORDS vs IUSE
.TP
\fB\-L\fR, \fB\-\-license\fR
Use the LICENSE vs IUSE
.TP
\fB\-D\fR, \fB\-\-describe\fR
Describe the USE flag
.TP
\fB\-F\fR \fI<arg>\fR, \fB\-\-format\fR \fI<arg>\fR
Use your own variable formats. -F NAME=
.TP
\fB\-N\fR, \fB\-\-name\-only\fR
Only show package name
.TP
\fB\-\-root\fR \fI<arg>\fR
Set the ROOT env var
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Make a lot of noise
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Tighter output; suppress warnings
.TP
\fB\-C\fR, \fB\-\-nocolor\fR
Don't output color
.TP
\fB\-h\fR, \fB\-\-help\fR
Print this help and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version and exit

.SH "REPORTING BUGS"
Please report bugs via http://bugs.gentoo.org/
.br
Product: Portage Development; Component: Tools
.SH AUTHORS
.nf
Ned Ludd <solar@gentoo.org>
Mike Frysinger <vapier@gentoo.org>
.fi
.SH "SEE ALSO"
.BR q (1),
.BR qatom (1),
.BR qcache (1),
.BR qcheck (1),
.BR qdepends (1),
.BR qfile (1),
.BR qgrep (1),
.BR qlist (1),
.BR qlop (1),
.BR qmerge (1),
.BR qpkg (1),
.BR qsearch (1),
.BR qsize (1),
.BR qtbz2 (1),
.BR qxpak (1)
