# Makefile.in generated by automake 1.15.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2017 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/portage-utils
pkgincludedir = $(includedir)/portage-utils
pkglibdir = $(libdir)/portage-utils
pkglibexecdir = $(libexecdir)/portage-utils
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-solaris2.11
host_triplet = x86_64-pc-solaris2.11
bin_PROGRAMS = q$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/autotools/m4/00gnulib.m4 \
	$(top_srcdir)/autotools/m4/absolute-header.m4 \
	$(top_srcdir)/autotools/m4/alloca.m4 \
	$(top_srcdir)/autotools/m4/canonicalize.m4 \
	$(top_srcdir)/autotools/m4/chdir-long.m4 \
	$(top_srcdir)/autotools/m4/clock_time.m4 \
	$(top_srcdir)/autotools/m4/close.m4 \
	$(top_srcdir)/autotools/m4/closedir.m4 \
	$(top_srcdir)/autotools/m4/dirent_h.m4 \
	$(top_srcdir)/autotools/m4/dirfd.m4 \
	$(top_srcdir)/autotools/m4/dirname.m4 \
	$(top_srcdir)/autotools/m4/double-slash-root.m4 \
	$(top_srcdir)/autotools/m4/dup.m4 \
	$(top_srcdir)/autotools/m4/dup2.m4 \
	$(top_srcdir)/autotools/m4/eealloc.m4 \
	$(top_srcdir)/autotools/m4/errno_h.m4 \
	$(top_srcdir)/autotools/m4/error.m4 \
	$(top_srcdir)/autotools/m4/euidaccess.m4 \
	$(top_srcdir)/autotools/m4/exponentd.m4 \
	$(top_srcdir)/autotools/m4/exponentf.m4 \
	$(top_srcdir)/autotools/m4/exponentl.m4 \
	$(top_srcdir)/autotools/m4/extensions.m4 \
	$(top_srcdir)/autotools/m4/extern-inline.m4 \
	$(top_srcdir)/autotools/m4/faccessat.m4 \
	$(top_srcdir)/autotools/m4/fchdir.m4 \
	$(top_srcdir)/autotools/m4/fcntl-o.m4 \
	$(top_srcdir)/autotools/m4/fcntl.m4 \
	$(top_srcdir)/autotools/m4/fcntl_h.m4 \
	$(top_srcdir)/autotools/m4/fdopendir.m4 \
	$(top_srcdir)/autotools/m4/filenamecat.m4 \
	$(top_srcdir)/autotools/m4/float_h.m4 \
	$(top_srcdir)/autotools/m4/fpieee.m4 \
	$(top_srcdir)/autotools/m4/frexp.m4 \
	$(top_srcdir)/autotools/m4/frexpl.m4 \
	$(top_srcdir)/autotools/m4/fstat.m4 \
	$(top_srcdir)/autotools/m4/fstatat.m4 \
	$(top_srcdir)/autotools/m4/futimens.m4 \
	$(top_srcdir)/autotools/m4/getcwd.m4 \
	$(top_srcdir)/autotools/m4/getdelim.m4 \
	$(top_srcdir)/autotools/m4/getdtablesize.m4 \
	$(top_srcdir)/autotools/m4/getgroups.m4 \
	$(top_srcdir)/autotools/m4/getline.m4 \
	$(top_srcdir)/autotools/m4/getopt.m4 \
	$(top_srcdir)/autotools/m4/getprogname.m4 \
	$(top_srcdir)/autotools/m4/gettime.m4 \
	$(top_srcdir)/autotools/m4/gettimeofday.m4 \
	$(top_srcdir)/autotools/m4/gnulib-common.m4 \
	$(top_srcdir)/autotools/m4/gnulib-comp.m4 \
	$(top_srcdir)/autotools/m4/group-member.m4 \
	$(top_srcdir)/autotools/m4/include_next.m4 \
	$(top_srcdir)/autotools/m4/intmax_t.m4 \
	$(top_srcdir)/autotools/m4/inttypes-pri.m4 \
	$(top_srcdir)/autotools/m4/inttypes.m4 \
	$(top_srcdir)/autotools/m4/inttypes_h.m4 \
	$(top_srcdir)/autotools/m4/isnand.m4 \
	$(top_srcdir)/autotools/m4/isnanf.m4 \
	$(top_srcdir)/autotools/m4/isnanl.m4 \
	$(top_srcdir)/autotools/m4/largefile.m4 \
	$(top_srcdir)/autotools/m4/ldexpl.m4 \
	$(top_srcdir)/autotools/m4/limits-h.m4 \
	$(top_srcdir)/autotools/m4/localtime-buffer.m4 \
	$(top_srcdir)/autotools/m4/longlong.m4 \
	$(top_srcdir)/autotools/m4/lstat.m4 \
	$(top_srcdir)/autotools/m4/malloc.m4 \
	$(top_srcdir)/autotools/m4/malloca.m4 \
	$(top_srcdir)/autotools/m4/math_h.m4 \
	$(top_srcdir)/autotools/m4/memchr.m4 \
	$(top_srcdir)/autotools/m4/mempcpy.m4 \
	$(top_srcdir)/autotools/m4/memrchr.m4 \
	$(top_srcdir)/autotools/m4/mkdir.m4 \
	$(top_srcdir)/autotools/m4/mkdirat.m4 \
	$(top_srcdir)/autotools/m4/mmap-anon.m4 \
	$(top_srcdir)/autotools/m4/mode_t.m4 \
	$(top_srcdir)/autotools/m4/msvc-inval.m4 \
	$(top_srcdir)/autotools/m4/msvc-nothrow.m4 \
	$(top_srcdir)/autotools/m4/multiarch.m4 \
	$(top_srcdir)/autotools/m4/nocrash.m4 \
	$(top_srcdir)/autotools/m4/off_t.m4 \
	$(top_srcdir)/autotools/m4/open-cloexec.m4 \
	$(top_srcdir)/autotools/m4/open.m4 \
	$(top_srcdir)/autotools/m4/openat.m4 \
	$(top_srcdir)/autotools/m4/opendir.m4 \
	$(top_srcdir)/autotools/m4/pathmax.m4 \
	$(top_srcdir)/autotools/m4/printf-frexp.m4 \
	$(top_srcdir)/autotools/m4/printf-frexpl.m4 \
	$(top_srcdir)/autotools/m4/printf.m4 \
	$(top_srcdir)/autotools/m4/readlink.m4 \
	$(top_srcdir)/autotools/m4/readlinkat.m4 \
	$(top_srcdir)/autotools/m4/realloc.m4 \
	$(top_srcdir)/autotools/m4/rename.m4 \
	$(top_srcdir)/autotools/m4/renameat.m4 \
	$(top_srcdir)/autotools/m4/rmdir.m4 \
	$(top_srcdir)/autotools/m4/save-cwd.m4 \
	$(top_srcdir)/autotools/m4/signbit.m4 \
	$(top_srcdir)/autotools/m4/size_max.m4 \
	$(top_srcdir)/autotools/m4/ssize_t.m4 \
	$(top_srcdir)/autotools/m4/stat-time.m4 \
	$(top_srcdir)/autotools/m4/stat.m4 \
	$(top_srcdir)/autotools/m4/stdbool.m4 \
	$(top_srcdir)/autotools/m4/stddef_h.m4 \
	$(top_srcdir)/autotools/m4/stdint.m4 \
	$(top_srcdir)/autotools/m4/stdint_h.m4 \
	$(top_srcdir)/autotools/m4/stdio_h.m4 \
	$(top_srcdir)/autotools/m4/stdlib_h.m4 \
	$(top_srcdir)/autotools/m4/stpcpy.m4 \
	$(top_srcdir)/autotools/m4/strcase.m4 \
	$(top_srcdir)/autotools/m4/strcasestr.m4 \
	$(top_srcdir)/autotools/m4/strdup.m4 \
	$(top_srcdir)/autotools/m4/strerror.m4 \
	$(top_srcdir)/autotools/m4/string_h.m4 \
	$(top_srcdir)/autotools/m4/strings_h.m4 \
	$(top_srcdir)/autotools/m4/strncat.m4 \
	$(top_srcdir)/autotools/m4/symlink.m4 \
	$(top_srcdir)/autotools/m4/symlinkat.m4 \
	$(top_srcdir)/autotools/m4/sys_socket_h.m4 \
	$(top_srcdir)/autotools/m4/sys_stat_h.m4 \
	$(top_srcdir)/autotools/m4/sys_time_h.m4 \
	$(top_srcdir)/autotools/m4/sys_types_h.m4 \
	$(top_srcdir)/autotools/m4/time_h.m4 \
	$(top_srcdir)/autotools/m4/timespec.m4 \
	$(top_srcdir)/autotools/m4/unistd-safer.m4 \
	$(top_srcdir)/autotools/m4/unistd_h.m4 \
	$(top_srcdir)/autotools/m4/unlink.m4 \
	$(top_srcdir)/autotools/m4/unlinkat.m4 \
	$(top_srcdir)/autotools/m4/utime.m4 \
	$(top_srcdir)/autotools/m4/utime_h.m4 \
	$(top_srcdir)/autotools/m4/utimens.m4 \
	$(top_srcdir)/autotools/m4/utimensat.m4 \
	$(top_srcdir)/autotools/m4/utimes.m4 \
	$(top_srcdir)/autotools/m4/vasnprintf.m4 \
	$(top_srcdir)/autotools/m4/vasprintf-posix.m4 \
	$(top_srcdir)/autotools/m4/vasprintf.m4 \
	$(top_srcdir)/autotools/m4/warn-on-use.m4 \
	$(top_srcdir)/autotools/m4/wchar_h.m4 \
	$(top_srcdir)/autotools/m4/wchar_t.m4 \
	$(top_srcdir)/autotools/m4/wint_t.m4 \
	$(top_srcdir)/autotools/m4/xsize.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(dist_postsyncd_SCRIPTS) \
	$(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(postsyncddir)" \
	"$(DESTDIR)$(man1dir)"
PROGRAMS = $(bin_PROGRAMS)
am_q_OBJECTS = q-main.$(OBJEXT)
q_OBJECTS = $(am_q_OBJECTS)
am__DEPENDENCIES_1 =
q_DEPENDENCIES = $(top_builddir)/autotools/gnulib/libgnu.a \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1)
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
SCRIPTS = $(dist_postsyncd_SCRIPTS)
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/autotools/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(q_SOURCES)
DIST_SOURCES = $(q_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
	ctags-recursive dvi-recursive html-recursive info-recursive \
	install-data-recursive install-dvi-recursive \
	install-exec-recursive install-html-recursive \
	install-info-recursive install-pdf-recursive \
	install-ps-recursive install-recursive installcheck-recursive \
	installdirs-recursive pdf-recursive ps-recursive \
	tags-recursive uninstall-recursive
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
man1dir = $(mandir)/man1
NROFF = nroff
MANS = $(dist_man_MANS)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
am__recursive_targets = \
  $(RECURSIVE_TARGETS) \
  $(RECURSIVE_CLEAN_TARGETS) \
  $(am__extra_recursive_targets)
AM_RECURSIVE_TARGETS = $(am__recursive_targets:-recursive=) TAGS CTAGS \
	cscope distdir dist dist-all distcheck
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
DIST_SUBDIRS = $(SUBDIRS)
am__DIST_COMMON = $(dist_man_MANS) $(srcdir)/Makefile.in \
	$(srcdir)/config.h.in $(top_srcdir)/autotools/compile \
	$(top_srcdir)/autotools/config.guess \
	$(top_srcdir)/autotools/config.sub \
	$(top_srcdir)/autotools/depcomp \
	$(top_srcdir)/autotools/install-sh \
	$(top_srcdir)/autotools/missing COPYING autotools/compile \
	autotools/config.guess autotools/config.sub autotools/depcomp \
	autotools/install-sh autotools/missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
GZIP_ENV = --best
DIST_ARCHIVES = $(distdir).tar.xz
DIST_TARGETS = dist-xz
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /net/ptah/export/gentoo/working-repos/portage-utils/autotools/missing aclocal-1.15
ALLOCA = 
ALLOCA_H = alloca.h
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
APPLE_UNIVERSAL_BUILD = 0
AR = ar
ARFLAGS = cr
AUTOCONF = ${SHELL} /net/ptah/export/gentoo/working-repos/portage-utils/autotools/missing autoconf
AUTOHEADER = ${SHELL} /net/ptah/export/gentoo/working-repos/portage-utils/autotools/missing autoheader
AUTOMAKE = ${SHELL} /net/ptah/export/gentoo/working-repos/portage-utils/autotools/missing automake-1.15
AWK = gawk
BITSIZEOF_PTRDIFF_T = 
BITSIZEOF_SIG_ATOMIC_T = 
BITSIZEOF_SIZE_T = 
BITSIZEOF_WCHAR_T = 
BITSIZEOF_WINT_T = 
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2 -Wall -Wunused -Wimplicit -Wshadow -Wformat=2 -Wmissing-declarations -Wno-missing-prototypes -Wwrite-strings -Wbad-function-cast -Wnested-externs -Wcomment -Winline -Wchar-subscripts -Wcast-align -Wno-format-nonliteral -Wsequence-point -Wold-style-definition -Wextra
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EGREP = /gentoo/prefix64/usr/bin/grep -E
EMULTIHOP_HIDDEN = 
EMULTIHOP_VALUE = 
ENOLINK_HIDDEN = 
ENOLINK_VALUE = 
EOVERFLOW_HIDDEN = 
EOVERFLOW_VALUE = 
ERRNO_H = 
EXEEXT = 
FLOAT_H = 
GETOPT_CDEFS_H = 
GETOPT_H = 
GNULIB_ACOSF = 0
GNULIB_ACOSL = 0
GNULIB_ALPHASORT = 0
GNULIB_ASINF = 0
GNULIB_ASINL = 0
GNULIB_ATAN2F = 0
GNULIB_ATANF = 0
GNULIB_ATANL = 0
GNULIB_ATOLL = 0
GNULIB_BTOWC = 0
GNULIB_CALLOC_POSIX = 0
GNULIB_CANONICALIZE_FILE_NAME = 1
GNULIB_CBRT = 0
GNULIB_CBRTF = 0
GNULIB_CBRTL = 0
GNULIB_CEIL = 0
GNULIB_CEILF = 0
GNULIB_CEILL = 0
GNULIB_CHDIR = 1
GNULIB_CHOWN = 0
GNULIB_CLOSE = 1
GNULIB_CLOSEDIR = 1
GNULIB_COPYSIGN = 0
GNULIB_COPYSIGNF = 0
GNULIB_COPYSIGNL = 0
GNULIB_COSF = 0
GNULIB_COSHF = 0
GNULIB_COSL = 0
GNULIB_CTIME = 0
GNULIB_DIRFD = 1
GNULIB_DPRINTF = 0
GNULIB_DUP = 1
GNULIB_DUP2 = 1
GNULIB_DUP3 = 0
GNULIB_ENVIRON = 0
GNULIB_EUIDACCESS = 1
GNULIB_EXP2 = 0
GNULIB_EXP2F = 0
GNULIB_EXP2L = 0
GNULIB_EXPF = 0
GNULIB_EXPL = 0
GNULIB_EXPLICIT_BZERO = 0
GNULIB_EXPM1 = 0
GNULIB_EXPM1F = 0
GNULIB_EXPM1L = 0
GNULIB_FABSF = 0
GNULIB_FABSL = 0
GNULIB_FACCESSAT = 1
GNULIB_FCHDIR = 1
GNULIB_FCHMODAT = 0
GNULIB_FCHOWNAT = 0
GNULIB_FCLOSE = 0
GNULIB_FCNTL = 1
GNULIB_FDATASYNC = 0
GNULIB_FDOPEN = 0
GNULIB_FDOPENDIR = 1
GNULIB_FFLUSH = 0
GNULIB_FFS = 0
GNULIB_FFSL = 0
GNULIB_FFSLL = 0
GNULIB_FGETC = 1
GNULIB_FGETS = 1
GNULIB_FLOOR = 0
GNULIB_FLOORF = 0
GNULIB_FLOORL = 0
GNULIB_FMA = 0
GNULIB_FMAF = 0
GNULIB_FMAL = 0
GNULIB_FMOD = 0
GNULIB_FMODF = 0
GNULIB_FMODL = 0
GNULIB_FOPEN = 0
GNULIB_FPRINTF = 1
GNULIB_FPRINTF_POSIX = 0
GNULIB_FPURGE = 0
GNULIB_FPUTC = 1
GNULIB_FPUTS = 1
GNULIB_FREAD = 1
GNULIB_FREOPEN = 0
GNULIB_FREXP = 1
GNULIB_FREXPF = 0
GNULIB_FREXPL = 1
GNULIB_FSCANF = 1
GNULIB_FSEEK = 0
GNULIB_FSEEKO = 0
GNULIB_FSTAT = 1
GNULIB_FSTATAT = 1
GNULIB_FSYNC = 0
GNULIB_FTELL = 0
GNULIB_FTELLO = 0
GNULIB_FTRUNCATE = 0
GNULIB_FUTIMENS = 1
GNULIB_FWRITE = 1
GNULIB_GETC = 1
GNULIB_GETCHAR = 1
GNULIB_GETCWD = 1
GNULIB_GETDELIM = 1
GNULIB_GETDOMAINNAME = 0
GNULIB_GETDTABLESIZE = 1
GNULIB_GETGROUPS = 1
GNULIB_GETHOSTNAME = 0
GNULIB_GETLINE = 1
GNULIB_GETLOADAVG = 0
GNULIB_GETLOGIN = 0
GNULIB_GETLOGIN_R = 0
GNULIB_GETPAGESIZE = 0
GNULIB_GETSUBOPT = 0
GNULIB_GETTIMEOFDAY = 1
GNULIB_GETUSERSHELL = 0
GNULIB_GL_UNISTD_H_GETOPT = 
GNULIB_GRANTPT = 0
GNULIB_GROUP_MEMBER = 1
GNULIB_HYPOT = 0
GNULIB_HYPOTF = 0
GNULIB_HYPOTL = 0
GNULIB_ILOGB = 0
GNULIB_ILOGBF = 0
GNULIB_ILOGBL = 0
GNULIB_IMAXABS = 0
GNULIB_IMAXDIV = 0
GNULIB_ISATTY = 0
GNULIB_ISFINITE = 0
GNULIB_ISINF = 0
GNULIB_ISNAN = 0
GNULIB_ISNAND = 0
GNULIB_ISNANF = 0
GNULIB_ISNANL = 0
GNULIB_LCHMOD = 0
GNULIB_LCHOWN = 0
GNULIB_LDEXPF = 0
GNULIB_LDEXPL = 0
GNULIB_LINK = 0
GNULIB_LINKAT = 0
GNULIB_LOCALTIME = 0
GNULIB_LOG = 0
GNULIB_LOG10 = 0
GNULIB_LOG10F = 0
GNULIB_LOG10L = 0
GNULIB_LOG1P = 0
GNULIB_LOG1PF = 0
GNULIB_LOG1PL = 0
GNULIB_LOG2 = 0
GNULIB_LOG2F = 0
GNULIB_LOG2L = 0
GNULIB_LOGB = 0
GNULIB_LOGBF = 0
GNULIB_LOGBL = 0
GNULIB_LOGF = 0
GNULIB_LOGL = 0
GNULIB_LSEEK = 0
GNULIB_LSTAT = 1
GNULIB_MALLOC_POSIX = 1
GNULIB_MBRLEN = 0
GNULIB_MBRTOWC = 0
GNULIB_MBSCASECMP = 0
GNULIB_MBSCASESTR = 0
GNULIB_MBSCHR = 0
GNULIB_MBSCSPN = 0
GNULIB_MBSINIT = 0
GNULIB_MBSLEN = 0
GNULIB_MBSNCASECMP = 0
GNULIB_MBSNLEN = 0
GNULIB_MBSNRTOWCS = 0
GNULIB_MBSPBRK = 0
GNULIB_MBSPCASECMP = 0
GNULIB_MBSRCHR = 0
GNULIB_MBSRTOWCS = 0
GNULIB_MBSSEP = 0
GNULIB_MBSSPN = 0
GNULIB_MBSSTR = 0
GNULIB_MBSTOK_R = 0
GNULIB_MBTOWC = 0
GNULIB_MEMCHR = 1
GNULIB_MEMMEM = 0
GNULIB_MEMPCPY = 1
GNULIB_MEMRCHR = 1
GNULIB_MKDIRAT = 1
GNULIB_MKDTEMP = 0
GNULIB_MKFIFO = 0
GNULIB_MKFIFOAT = 0
GNULIB_MKNOD = 0
GNULIB_MKNODAT = 0
GNULIB_MKOSTEMP = 0
GNULIB_MKOSTEMPS = 0
GNULIB_MKSTEMP = 0
GNULIB_MKSTEMPS = 0
GNULIB_MKTIME = 0
GNULIB_MODF = 0
GNULIB_MODFF = 0
GNULIB_MODFL = 0
GNULIB_NANOSLEEP = 0
GNULIB_NONBLOCKING = 0
GNULIB_OBSTACK_PRINTF = 0
GNULIB_OBSTACK_PRINTF_POSIX = 0
GNULIB_OPEN = 1
GNULIB_OPENAT = 1
GNULIB_OPENDIR = 1
GNULIB_OVERRIDES_STRUCT_STAT = 0
GNULIB_OVERRIDES_WINT_T = 0
GNULIB_PCLOSE = 0
GNULIB_PERROR = 0
GNULIB_PIPE = 0
GNULIB_PIPE2 = 0
GNULIB_POPEN = 0
GNULIB_POSIX_OPENPT = 0
GNULIB_POWF = 0
GNULIB_PREAD = 0
GNULIB_PRINTF = 1
GNULIB_PRINTF_POSIX = 0
GNULIB_PTSNAME = 0
GNULIB_PTSNAME_R = 0
GNULIB_PUTC = 1
GNULIB_PUTCHAR = 1
GNULIB_PUTENV = 0
GNULIB_PUTS = 1
GNULIB_PWRITE = 0
GNULIB_QSORT_R = 0
GNULIB_RANDOM = 0
GNULIB_RANDOM_R = 0
GNULIB_RAWMEMCHR = 0
GNULIB_READ = 0
GNULIB_READDIR = 0
GNULIB_READLINK = 1
GNULIB_READLINKAT = 1
GNULIB_REALLOCARRAY = 0
GNULIB_REALLOC_POSIX = 1
GNULIB_REALPATH = 1
GNULIB_REMAINDER = 0
GNULIB_REMAINDERF = 0
GNULIB_REMAINDERL = 0
GNULIB_REMOVE = 0
GNULIB_RENAME = 1
GNULIB_RENAMEAT = 1
GNULIB_REWINDDIR = 0
GNULIB_RINT = 0
GNULIB_RINTF = 0
GNULIB_RINTL = 0
GNULIB_RMDIR = 1
GNULIB_ROUND = 0
GNULIB_ROUNDF = 0
GNULIB_ROUNDL = 0
GNULIB_RPMATCH = 0
GNULIB_SCANDIR = 0
GNULIB_SCANF = 1
GNULIB_SECURE_GETENV = 0
GNULIB_SETENV = 0
GNULIB_SETHOSTNAME = 0
GNULIB_SIGNBIT = 1
GNULIB_SINF = 0
GNULIB_SINHF = 0
GNULIB_SINL = 0
GNULIB_SLEEP = 0
GNULIB_SNPRINTF = 0
GNULIB_SPRINTF_POSIX = 0
GNULIB_SQRTF = 0
GNULIB_SQRTL = 0
GNULIB_STAT = 1
GNULIB_STDIO_H_NONBLOCKING = 0
GNULIB_STDIO_H_SIGPIPE = 0
GNULIB_STPCPY = 1
GNULIB_STPNCPY = 0
GNULIB_STRCASESTR = 1
GNULIB_STRCHRNUL = 0
GNULIB_STRDUP = 1
GNULIB_STRERROR = 1
GNULIB_STRERROR_R = 0
GNULIB_STRFTIME = 0
GNULIB_STRNCAT = 1
GNULIB_STRNDUP = 0
GNULIB_STRNLEN = 0
GNULIB_STRPBRK = 0
GNULIB_STRPTIME = 0
GNULIB_STRSEP = 0
GNULIB_STRSIGNAL = 0
GNULIB_STRSTR = 0
GNULIB_STRTOD = 0
GNULIB_STRTOIMAX = 0
GNULIB_STRTOK_R = 0
GNULIB_STRTOLL = 0
GNULIB_STRTOULL = 0
GNULIB_STRTOUMAX = 0
GNULIB_STRVERSCMP = 0
GNULIB_SYMLINK = 1
GNULIB_SYMLINKAT = 1
GNULIB_SYSTEM_POSIX = 0
GNULIB_TANF = 0
GNULIB_TANHF = 0
GNULIB_TANL = 0
GNULIB_TIMEGM = 0
GNULIB_TIME_R = 0
GNULIB_TIME_RZ = 0
GNULIB_TMPFILE = 0
GNULIB_TRUNC = 0
GNULIB_TRUNCATE = 0
GNULIB_TRUNCF = 0
GNULIB_TRUNCL = 0
GNULIB_TTYNAME_R = 0
GNULIB_TZSET = 0
GNULIB_UNISTD_H_NONBLOCKING = 0
GNULIB_UNISTD_H_SIGPIPE = 0
GNULIB_UNLINK = 1
GNULIB_UNLINKAT = 1
GNULIB_UNLOCKPT = 0
GNULIB_UNSETENV = 0
GNULIB_USLEEP = 0
GNULIB_UTIME = 1
GNULIB_UTIMENSAT = 1
GNULIB_VASPRINTF = 1
GNULIB_VDPRINTF = 0
GNULIB_VFPRINTF = 1
GNULIB_VFPRINTF_POSIX = 0
GNULIB_VFSCANF = 0
GNULIB_VPRINTF = 1
GNULIB_VPRINTF_POSIX = 0
GNULIB_VSCANF = 0
GNULIB_VSNPRINTF = 0
GNULIB_VSPRINTF_POSIX = 0
GNULIB_WCPCPY = 0
GNULIB_WCPNCPY = 0
GNULIB_WCRTOMB = 0
GNULIB_WCSCASECMP = 0
GNULIB_WCSCAT = 0
GNULIB_WCSCHR = 0
GNULIB_WCSCMP = 0
GNULIB_WCSCOLL = 0
GNULIB_WCSCPY = 0
GNULIB_WCSCSPN = 0
GNULIB_WCSDUP = 0
GNULIB_WCSFTIME = 0
GNULIB_WCSLEN = 0
GNULIB_WCSNCASECMP = 0
GNULIB_WCSNCAT = 0
GNULIB_WCSNCMP = 0
GNULIB_WCSNCPY = 0
GNULIB_WCSNLEN = 0
GNULIB_WCSNRTOMBS = 0
GNULIB_WCSPBRK = 0
GNULIB_WCSRCHR = 0
GNULIB_WCSRTOMBS = 0
GNULIB_WCSSPN = 0
GNULIB_WCSSTR = 0
GNULIB_WCSTOK = 0
GNULIB_WCSWIDTH = 0
GNULIB_WCSXFRM = 0
GNULIB_WCTOB = 0
GNULIB_WCTOMB = 0
GNULIB_WCWIDTH = 0
GNULIB_WMEMCHR = 0
GNULIB_WMEMCMP = 0
GNULIB_WMEMCPY = 0
GNULIB_WMEMMOVE = 0
GNULIB_WMEMSET = 0
GNULIB_WRITE = 0
GNULIB__EXIT = 0
GREP = /gentoo/prefix64/usr/bin/grep
HAVE_ACOSF = 1
HAVE_ACOSL = 1
HAVE_ALPHASORT = 1
HAVE_ASINF = 1
HAVE_ASINL = 1
HAVE_ATAN2F = 1
HAVE_ATANF = 1
HAVE_ATANL = 1
HAVE_ATOLL = 1
HAVE_BTOWC = 1
HAVE_C99_STDINT_H = 1
HAVE_CANONICALIZE_FILE_NAME = 1
HAVE_CBRT = 1
HAVE_CBRTF = 1
HAVE_CBRTL = 1
HAVE_CHOWN = 1
HAVE_CLOSEDIR = 1
HAVE_COPYSIGN = 1
HAVE_COPYSIGNL = 1
HAVE_COSF = 1
HAVE_COSHF = 1
HAVE_COSL = 1
HAVE_CRTDEFS_H = 0
HAVE_DECL_ACOSL = 1
HAVE_DECL_ASINL = 1
HAVE_DECL_ATANL = 1
HAVE_DECL_CBRTF = 1
HAVE_DECL_CBRTL = 1
HAVE_DECL_CEILF = 1
HAVE_DECL_CEILL = 1
HAVE_DECL_COPYSIGNF = 1
HAVE_DECL_COSL = 1
HAVE_DECL_DIRFD = 1
HAVE_DECL_ENVIRON = 1
HAVE_DECL_EXP2 = 1
HAVE_DECL_EXP2F = 1
HAVE_DECL_EXP2L = 1
HAVE_DECL_EXPL = 1
HAVE_DECL_EXPM1L = 1
HAVE_DECL_FCHDIR = 1
HAVE_DECL_FDATASYNC = 1
HAVE_DECL_FDOPENDIR = 1
HAVE_DECL_FLOORF = 1
HAVE_DECL_FLOORL = 1
HAVE_DECL_FPURGE = 1
HAVE_DECL_FREXPL = 1
HAVE_DECL_FSEEKO = 1
HAVE_DECL_FTELLO = 1
HAVE_DECL_GETDELIM = 1
HAVE_DECL_GETDOMAINNAME = 1
HAVE_DECL_GETLINE = 1
HAVE_DECL_GETLOADAVG = 1
HAVE_DECL_GETLOGIN = 1
HAVE_DECL_GETLOGIN_R = 1
HAVE_DECL_GETPAGESIZE = 1
HAVE_DECL_GETUSERSHELL = 1
HAVE_DECL_IMAXABS = 1
HAVE_DECL_IMAXDIV = 1
HAVE_DECL_INITSTATE = 1
HAVE_DECL_LDEXPL = 1
HAVE_DECL_LOCALTIME_R = 1
HAVE_DECL_LOG10L = 1
HAVE_DECL_LOG2 = 1
HAVE_DECL_LOG2F = 1
HAVE_DECL_LOG2L = 1
HAVE_DECL_LOGB = 1
HAVE_DECL_LOGL = 1
HAVE_DECL_MEMMEM = 1
HAVE_DECL_MEMRCHR = 0
HAVE_DECL_OBSTACK_PRINTF = 1
HAVE_DECL_REMAINDER = 1
HAVE_DECL_REMAINDERL = 1
HAVE_DECL_RINTF = 1
HAVE_DECL_ROUND = 1
HAVE_DECL_ROUNDF = 1
HAVE_DECL_ROUNDL = 1
HAVE_DECL_SETENV = 1
HAVE_DECL_SETHOSTNAME = 1
HAVE_DECL_SETSTATE = 1
HAVE_DECL_SINL = 1
HAVE_DECL_SNPRINTF = 1
HAVE_DECL_SQRTL = 1
HAVE_DECL_STRDUP = 1
HAVE_DECL_STRERROR_R = 1
HAVE_DECL_STRNCASECMP = 1
HAVE_DECL_STRNDUP = 1
HAVE_DECL_STRNLEN = 1
HAVE_DECL_STRSIGNAL = 1
HAVE_DECL_STRTOIMAX = 1
HAVE_DECL_STRTOK_R = 1
HAVE_DECL_STRTOUMAX = 1
HAVE_DECL_TANL = 1
HAVE_DECL_TRUNC = 1
HAVE_DECL_TRUNCF = 1
HAVE_DECL_TRUNCL = 1
HAVE_DECL_TTYNAME_R = 1
HAVE_DECL_UNSETENV = 1
HAVE_DECL_VSNPRINTF = 1
HAVE_DECL_WCTOB = 1
HAVE_DECL_WCWIDTH = 1
HAVE_DIRENT_H = 1
HAVE_DPRINTF = 1
HAVE_DUP2 = 1
HAVE_DUP3 = 1
HAVE_EUIDACCESS = 0
HAVE_EXPF = 1
HAVE_EXPL = 1
HAVE_EXPLICIT_BZERO = 1
HAVE_EXPM1 = 1
HAVE_EXPM1F = 1
HAVE_FABSF = 1
HAVE_FABSL = 1
HAVE_FACCESSAT = 1
HAVE_FCHDIR = 1
HAVE_FCHMODAT = 1
HAVE_FCHOWNAT = 1
HAVE_FCNTL = 1
HAVE_FDATASYNC = 1
HAVE_FDOPENDIR = 1
HAVE_FEATURES_H = 0
HAVE_FFS = 1
HAVE_FFSL = 1
HAVE_FFSLL = 1
HAVE_FMA = 1
HAVE_FMAF = 1
HAVE_FMAL = 1
HAVE_FMODF = 1
HAVE_FMODL = 1
HAVE_FREXPF = 1
HAVE_FSEEKO = 1
HAVE_FSTATAT = 1
HAVE_FSYNC = 1
HAVE_FTELLO = 1
HAVE_FTRUNCATE = 1
HAVE_FUTIMENS = 1
HAVE_GETDTABLESIZE = 1
HAVE_GETGROUPS = 1
HAVE_GETHOSTNAME = 1
HAVE_GETLOGIN = 1
HAVE_GETOPT_H = 1
HAVE_GETPAGESIZE = 1
HAVE_GETSUBOPT = 1
HAVE_GETTIMEOFDAY = 1
HAVE_GRANTPT = 1
HAVE_GROUP_MEMBER = 0
HAVE_HYPOTF = 1
HAVE_HYPOTL = 1
HAVE_ILOGB = 1
HAVE_ILOGBF = 1
HAVE_ILOGBL = 1
HAVE_INTTYPES_H = 1
HAVE_ISNAND = 1
HAVE_ISNANF = 1
HAVE_ISNANL = 1
HAVE_LCHMOD = 1
HAVE_LCHOWN = 1
HAVE_LDEXPF = 1
HAVE_LINK = 1
HAVE_LINKAT = 1
HAVE_LOG10F = 1
HAVE_LOG10L = 1
HAVE_LOG1P = 1
HAVE_LOG1PF = 1
HAVE_LOG1PL = 1
HAVE_LOGBF = 1
HAVE_LOGBL = 1
HAVE_LOGF = 1
HAVE_LOGL = 1
HAVE_LONG_LONG_INT = 1
HAVE_LSTAT = 1
HAVE_MAX_ALIGN_T = 1
HAVE_MBRLEN = 1
HAVE_MBRTOWC = 1
HAVE_MBSINIT = 1
HAVE_MBSLEN = 0
HAVE_MBSNRTOWCS = 1
HAVE_MBSRTOWCS = 1
HAVE_MEMCHR = 1
HAVE_MEMPCPY = 0
HAVE_MKDIRAT = 1
HAVE_MKDTEMP = 1
HAVE_MKFIFO = 1
HAVE_MKFIFOAT = 1
HAVE_MKNOD = 1
HAVE_MKNODAT = 1
HAVE_MKOSTEMP = 1
HAVE_MKOSTEMPS = 1
HAVE_MKSTEMP = 1
HAVE_MKSTEMPS = 1
HAVE_MODFF = 1
HAVE_MODFL = 1
HAVE_MSVC_INVALID_PARAMETER_HANDLER = 0
HAVE_NANOSLEEP = 1
HAVE_OPENAT = 1
HAVE_OPENDIR = 1
HAVE_OS_H = 0
HAVE_PCLOSE = 1
HAVE_PIPE = 1
HAVE_PIPE2 = 1
HAVE_POPEN = 1
HAVE_POSIX_OPENPT = 1
HAVE_POWF = 1
HAVE_PREAD = 1
HAVE_PTSNAME = 1
HAVE_PTSNAME_R = 1
HAVE_PWRITE = 1
HAVE_QSORT_R = 1
HAVE_RANDOM = 1
HAVE_RANDOM_H = 1
HAVE_RANDOM_R = 1
HAVE_RAWMEMCHR = 1
HAVE_READDIR = 1
HAVE_READLINK = 1
HAVE_READLINKAT = 1
HAVE_REALLOCARRAY = 1
HAVE_REALPATH = 1
HAVE_REMAINDER = 1
HAVE_REMAINDERF = 1
HAVE_RENAMEAT = 1
HAVE_REWINDDIR = 1
HAVE_RINT = 1
HAVE_RINTL = 1
HAVE_RPMATCH = 1
HAVE_SAME_LONG_DOUBLE_AS_DOUBLE = 0
HAVE_SCANDIR = 1
HAVE_SECURE_GETENV = 1
HAVE_SETENV = 1
HAVE_SETHOSTNAME = 1
HAVE_SIGNED_SIG_ATOMIC_T = 
HAVE_SIGNED_WCHAR_T = 
HAVE_SIGNED_WINT_T = 
HAVE_SINF = 1
HAVE_SINHF = 1
HAVE_SINL = 1
HAVE_SLEEP = 1
HAVE_SQRTF = 1
HAVE_SQRTL = 1
HAVE_STDINT_H = 1
HAVE_STPCPY = 1
HAVE_STPNCPY = 1
HAVE_STRCASECMP = 1
HAVE_STRCASESTR = 1
HAVE_STRCHRNUL = 1
HAVE_STRINGS_H = 1
HAVE_STRPBRK = 1
HAVE_STRPTIME = 1
HAVE_STRSEP = 1
HAVE_STRTOD = 1
HAVE_STRTOLL = 1
HAVE_STRTOULL = 1
HAVE_STRUCT_RANDOM_DATA = 1
HAVE_STRUCT_TIMEVAL = 1
HAVE_STRVERSCMP = 1
HAVE_SYMLINK = 1
HAVE_SYMLINKAT = 1
HAVE_SYS_BITYPES_H = 0
HAVE_SYS_CDEFS_H = 
HAVE_SYS_INTTYPES_H = 0
HAVE_SYS_LOADAVG_H = 0
HAVE_SYS_PARAM_H = 0
HAVE_SYS_TIME_H = 1
HAVE_SYS_TYPES_H = 1
HAVE_TANF = 1
HAVE_TANHF = 1
HAVE_TANL = 1
HAVE_TIMEGM = 1
HAVE_TIMEZONE_T = 0
HAVE_TRUNCATE = 1
HAVE_TZSET = 1
HAVE_UNISTD_H = 1
HAVE_UNLINKAT = 1
HAVE_UNLOCKPT = 1
HAVE_UNSIGNED_LONG_LONG_INT = 1
HAVE_USLEEP = 1
HAVE_UTIME = 1
HAVE_UTIMENSAT = 1
HAVE_UTIME_H = 1
HAVE_VASPRINTF = 1
HAVE_VDPRINTF = 1
HAVE_WCHAR_H = 1
HAVE_WCHAR_T = 1
HAVE_WCPCPY = 1
HAVE_WCPNCPY = 1
HAVE_WCRTOMB = 1
HAVE_WCSCASECMP = 1
HAVE_WCSCAT = 1
HAVE_WCSCHR = 1
HAVE_WCSCMP = 1
HAVE_WCSCOLL = 1
HAVE_WCSCPY = 1
HAVE_WCSCSPN = 1
HAVE_WCSDUP = 1
HAVE_WCSFTIME = 1
HAVE_WCSLEN = 1
HAVE_WCSNCASECMP = 1
HAVE_WCSNCAT = 1
HAVE_WCSNCMP = 1
HAVE_WCSNCPY = 1
HAVE_WCSNLEN = 1
HAVE_WCSNRTOMBS = 1
HAVE_WCSPBRK = 1
HAVE_WCSRCHR = 1
HAVE_WCSRTOMBS = 1
HAVE_WCSSPN = 1
HAVE_WCSSTR = 1
HAVE_WCSTOK = 1
HAVE_WCSWIDTH = 1
HAVE_WCSXFRM = 1
HAVE_WINSOCK2_H = 0
HAVE_WINT_T = 1
HAVE_WMEMCHR = 1
HAVE_WMEMCMP = 1
HAVE_WMEMCPY = 1
HAVE_WMEMMOVE = 1
HAVE_WMEMSET = 1
HAVE__BOOL = 1
HAVE__EXIT = 1
INCLUDE_NEXT = include_next
INCLUDE_NEXT_AS_FIRST_DIRECTIVE = include_next
INSTALL = /gentoo/prefix64/usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
INT32_MAX_LT_INTMAX_MAX = 1
INT64_MAX_EQ_LONG_MAX = 1
LDFLAGS = 
LIBGNU_LIBDEPS = 
LIBGNU_LTLIBDEPS = 
LIBINTL = 
LIBOBJS = 
LIBS = -lkvm 
LIB_CLOCK_GETTIME = 
LIB_EACCESS = -lgen
LIMITS_H = limits.h
LTLIBINTL = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /net/ptah/export/gentoo/working-repos/portage-utils/autotools/missing makeinfo
MKDIR_P = /gentoo/prefix64/usr/bin/mkdir -p
NEXT_AS_FIRST_DIRECTIVE_DIRENT_H = <dirent.h>
NEXT_AS_FIRST_DIRECTIVE_ERRNO_H = 
NEXT_AS_FIRST_DIRECTIVE_FCNTL_H = <fcntl.h>
NEXT_AS_FIRST_DIRECTIVE_FLOAT_H = 
NEXT_AS_FIRST_DIRECTIVE_GETOPT_H = <getopt.h>
NEXT_AS_FIRST_DIRECTIVE_INTTYPES_H = <inttypes.h>
NEXT_AS_FIRST_DIRECTIVE_LIMITS_H = <limits.h>
NEXT_AS_FIRST_DIRECTIVE_MATH_H = <math.h>
NEXT_AS_FIRST_DIRECTIVE_STDDEF_H = 
NEXT_AS_FIRST_DIRECTIVE_STDINT_H = <stdint.h>
NEXT_AS_FIRST_DIRECTIVE_STDIO_H = <stdio.h>
NEXT_AS_FIRST_DIRECTIVE_STDLIB_H = <stdlib.h>
NEXT_AS_FIRST_DIRECTIVE_STRINGS_H = <strings.h>
NEXT_AS_FIRST_DIRECTIVE_STRING_H = <string.h>
NEXT_AS_FIRST_DIRECTIVE_SYS_STAT_H = <sys/stat.h>
NEXT_AS_FIRST_DIRECTIVE_SYS_TIME_H = <sys/time.h>
NEXT_AS_FIRST_DIRECTIVE_SYS_TYPES_H = <sys/types.h>
NEXT_AS_FIRST_DIRECTIVE_TIME_H = <time.h>
NEXT_AS_FIRST_DIRECTIVE_UNISTD_H = <unistd.h>
NEXT_AS_FIRST_DIRECTIVE_UTIME_H = <utime.h>
NEXT_AS_FIRST_DIRECTIVE_WCHAR_H = <wchar.h>
NEXT_DIRENT_H = <dirent.h>
NEXT_ERRNO_H = 
NEXT_FCNTL_H = <fcntl.h>
NEXT_FLOAT_H = 
NEXT_GETOPT_H = <getopt.h>
NEXT_INTTYPES_H = <inttypes.h>
NEXT_LIMITS_H = <limits.h>
NEXT_MATH_H = <math.h>
NEXT_STDDEF_H = 
NEXT_STDINT_H = <stdint.h>
NEXT_STDIO_H = <stdio.h>
NEXT_STDLIB_H = <stdlib.h>
NEXT_STRINGS_H = <strings.h>
NEXT_STRING_H = <string.h>
NEXT_SYS_STAT_H = <sys/stat.h>
NEXT_SYS_TIME_H = <sys/time.h>
NEXT_SYS_TYPES_H = <sys/types.h>
NEXT_TIME_H = <time.h>
NEXT_UNISTD_H = <unistd.h>
NEXT_UTIME_H = <utime.h>
NEXT_WCHAR_H = <wchar.h>
OBJEXT = o
PACKAGE = portage-utils
PACKAGE_BUGREPORT = 
PACKAGE_NAME = portage-utils
PACKAGE_STRING = portage-utils git
PACKAGE_TARNAME = portage-utils
PACKAGE_URL = 
PACKAGE_VERSION = git
PATH_SEPARATOR = :
PRAGMA_COLUMNS = 
PRAGMA_SYSTEM_HEADER = #pragma GCC system_header
PRIPTR_PREFIX = "l"
PRI_MACROS_BROKEN = 0
PTHREAD_H_DEFINES_STRUCT_TIMESPEC = 0
PTRDIFF_T_SUFFIX = 
RANLIB = ranlib
REPLACE_ACOSF = 0
REPLACE_ASINF = 0
REPLACE_ATAN2F = 0
REPLACE_ATANF = 0
REPLACE_BTOWC = 0
REPLACE_CALLOC = 0
REPLACE_CANONICALIZE_FILE_NAME = 0
REPLACE_CBRTF = 0
REPLACE_CBRTL = 0
REPLACE_CEIL = 0
REPLACE_CEILF = 0
REPLACE_CEILL = 0
REPLACE_CHOWN = 0
REPLACE_CLOSE = 0
REPLACE_CLOSEDIR = 0
REPLACE_COSF = 0
REPLACE_COSHF = 0
REPLACE_CTIME = GNULIB_PORTCHECK
REPLACE_DIRFD = 0
REPLACE_DPRINTF = 0
REPLACE_DUP = 0
REPLACE_DUP2 = 0
REPLACE_EXP2 = 0
REPLACE_EXP2L = 0
REPLACE_EXPF = 0
REPLACE_EXPM1 = 0
REPLACE_EXPM1F = 0
REPLACE_FABSL = 0
REPLACE_FACCESSAT = 0
REPLACE_FCHOWNAT = 0
REPLACE_FCLOSE = 0
REPLACE_FCNTL = 0
REPLACE_FDOPEN = 0
REPLACE_FDOPENDIR = 0
REPLACE_FFLUSH = 0
REPLACE_FLOOR = 0
REPLACE_FLOORF = 0
REPLACE_FLOORL = 0
REPLACE_FMA = 0
REPLACE_FMAF = 0
REPLACE_FMAL = 0
REPLACE_FMOD = 0
REPLACE_FMODF = 0
REPLACE_FMODL = 0
REPLACE_FOPEN = 0
REPLACE_FPRINTF = 0
REPLACE_FPURGE = 0
REPLACE_FREOPEN = 0
REPLACE_FREXP = 0
REPLACE_FREXPF = 0
REPLACE_FREXPL = 1
REPLACE_FSEEK = 0
REPLACE_FSEEKO = 0
REPLACE_FSTAT = 1
REPLACE_FSTATAT = 1
REPLACE_FTELL = 0
REPLACE_FTELLO = 0
REPLACE_FTRUNCATE = 0
REPLACE_FUTIMENS = 1
REPLACE_GETCWD = 1
REPLACE_GETDELIM = 0
REPLACE_GETDOMAINNAME = 0
REPLACE_GETDTABLESIZE = 0
REPLACE_GETGROUPS = 0
REPLACE_GETLINE = 0
REPLACE_GETLOGIN_R = 0
REPLACE_GETPAGESIZE = 0
REPLACE_GETTIMEOFDAY = 0
REPLACE_GMTIME = 0
REPLACE_HUGE_VAL = 0
REPLACE_HYPOT = 0
REPLACE_HYPOTF = 0
REPLACE_HYPOTL = 0
REPLACE_ILOGB = 0
REPLACE_ILOGBF = 0
REPLACE_ILOGBL = 0
REPLACE_ISATTY = 0
REPLACE_ISFINITE = 0
REPLACE_ISINF = 0
REPLACE_ISNAN = 0
REPLACE_ITOLD = 0
REPLACE_LCHOWN = 0
REPLACE_LDEXPL = 0
REPLACE_LINK = 0
REPLACE_LINKAT = 0
REPLACE_LOCALTIME = 0
REPLACE_LOCALTIME_R = GNULIB_PORTCHECK
REPLACE_LOG = 0
REPLACE_LOG10 = 0
REPLACE_LOG10F = 0
REPLACE_LOG10L = 0
REPLACE_LOG1P = 0
REPLACE_LOG1PF = 0
REPLACE_LOG1PL = 0
REPLACE_LOG2 = 0
REPLACE_LOG2F = 0
REPLACE_LOG2L = 0
REPLACE_LOGB = 0
REPLACE_LOGBF = 0
REPLACE_LOGBL = 0
REPLACE_LOGF = 0
REPLACE_LOGL = 0
REPLACE_LSEEK = 0
REPLACE_LSTAT = 1
REPLACE_MALLOC = 0
REPLACE_MBRLEN = 0
REPLACE_MBRTOWC = 0
REPLACE_MBSINIT = 0
REPLACE_MBSNRTOWCS = 0
REPLACE_MBSRTOWCS = 0
REPLACE_MBSTATE_T = 0
REPLACE_MBTOWC = 0
REPLACE_MEMCHR = 0
REPLACE_MEMMEM = 0
REPLACE_MKDIR = 0
REPLACE_MKFIFO = 0
REPLACE_MKNOD = 0
REPLACE_MKSTEMP = 0
REPLACE_MKTIME = GNULIB_PORTCHECK
REPLACE_MODF = 0
REPLACE_MODFF = 0
REPLACE_MODFL = 0
REPLACE_NAN = 0
REPLACE_NANOSLEEP = GNULIB_PORTCHECK
REPLACE_NULL = 0
REPLACE_OBSTACK_PRINTF = 0
REPLACE_OPEN = 0
REPLACE_OPENAT = 0
REPLACE_OPENDIR = 0
REPLACE_PERROR = 0
REPLACE_POPEN = 0
REPLACE_PREAD = 0
REPLACE_PRINTF = 0
REPLACE_PTSNAME = 0
REPLACE_PTSNAME_R = 0
REPLACE_PUTENV = 0
REPLACE_PWRITE = 0
REPLACE_QSORT_R = 0
REPLACE_RANDOM_R = 0
REPLACE_READ = 0
REPLACE_READLINK = 0
REPLACE_READLINKAT = 0
REPLACE_REALLOC = 0
REPLACE_REALPATH = 0
REPLACE_REMAINDER = 0
REPLACE_REMAINDERF = 0
REPLACE_REMAINDERL = 0
REPLACE_REMOVE = 0
REPLACE_RENAME = 1
REPLACE_RENAMEAT = 1
REPLACE_RMDIR = 0
REPLACE_ROUND = 0
REPLACE_ROUNDF = 0
REPLACE_ROUNDL = 0
REPLACE_SETENV = 0
REPLACE_SIGNBIT = 0
REPLACE_SIGNBIT_USING_GCC = 1
REPLACE_SINF = 0
REPLACE_SINHF = 0
REPLACE_SLEEP = 0
REPLACE_SNPRINTF = 0
REPLACE_SPRINTF = 0
REPLACE_SQRTF = 0
REPLACE_SQRTL = 0
REPLACE_STAT = 0
REPLACE_STDIO_READ_FUNCS = 0
REPLACE_STDIO_WRITE_FUNCS = 0
REPLACE_STPNCPY = 0
REPLACE_STRCASESTR = 0
REPLACE_STRCHRNUL = 0
REPLACE_STRDUP = 0
REPLACE_STRERROR = 0
REPLACE_STRERROR_R = 0
REPLACE_STRFTIME = GNULIB_PORTCHECK
REPLACE_STRNCAT = 0
REPLACE_STRNDUP = 0
REPLACE_STRNLEN = 0
REPLACE_STRSIGNAL = 0
REPLACE_STRSTR = 0
REPLACE_STRTOD = 0
REPLACE_STRTOIMAX = 0
REPLACE_STRTOK_R = 0
REPLACE_STRTOUMAX = 0
REPLACE_STRUCT_TIMEVAL = 0
REPLACE_SYMLINK = 0
REPLACE_SYMLINKAT = 0
REPLACE_TANF = 0
REPLACE_TANHF = 0
REPLACE_TIMEGM = GNULIB_PORTCHECK
REPLACE_TMPFILE = 0
REPLACE_TRUNC = 0
REPLACE_TRUNCATE = 0
REPLACE_TRUNCF = 0
REPLACE_TRUNCL = 0
REPLACE_TTYNAME_R = 0
REPLACE_TZSET = GNULIB_PORTCHECK
REPLACE_UNLINK = 0
REPLACE_UNLINKAT = 0
REPLACE_UNSETENV = 0
REPLACE_USLEEP = 0
REPLACE_UTIME = 0
REPLACE_UTIMENSAT = 0
REPLACE_VASPRINTF = 1
REPLACE_VDPRINTF = 0
REPLACE_VFPRINTF = 0
REPLACE_VPRINTF = 0
REPLACE_VSNPRINTF = 0
REPLACE_VSPRINTF = 0
REPLACE_WCRTOMB = 0
REPLACE_WCSFTIME = 0
REPLACE_WCSNRTOMBS = 0
REPLACE_WCSRTOMBS = 0
REPLACE_WCSWIDTH = 0
REPLACE_WCTOB = 0
REPLACE_WCTOMB = 0
REPLACE_WCWIDTH = 0
REPLACE_WRITE = 0
SET_MAKE = 
SHELL = /bin/sh
SIG_ATOMIC_T_SUFFIX = 
SIZE_T_SUFFIX = 
STDBOOL_H = 
STDDEF_H = 
STDINT_H = stdint.h
STRIP = 
SYS_TIME_H_DEFINES_STRUCT_TIMESPEC = 0
TIME_H_DEFINES_STRUCT_TIMESPEC = 1
UINT32_MAX_LT_UINTMAX_MAX = 1
UINT64_MAX_EQ_ULONG_MAX = 1
UNDEFINE_STRTOK_R = 0
UNISTD_H_DEFINES_STRUCT_TIMESPEC = 0
UNISTD_H_HAVE_WINSOCK2_H = 0
UNISTD_H_HAVE_WINSOCK2_H_AND_USE_SOCKETS = 0
UTIME_H = 
VERSION = git
WCHAR_T_SUFFIX = 
WINDOWS_64_BIT_OFF_T = 0
WINDOWS_64_BIT_ST_SIZE = 0
WINDOWS_STAT_INODES = 0
WINDOWS_STAT_TIMESPEC = 0
WINT_T_SUFFIX = 
abs_builddir = /net/ptah/export/gentoo/working-repos/portage-utils
abs_srcdir = /net/ptah/export/gentoo/working-repos/portage-utils
abs_top_builddir = /net/ptah/export/gentoo/working-repos/portage-utils
abs_top_srcdir = /net/ptah/export/gentoo/working-repos/portage-utils
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-pc-solaris2.11
build_alias = 
build_cpu = x86_64
build_os = solaris2.11
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
gl_LIBOBJS =  asnprintf.o asprintf.o chdir-long.o error.o euidaccess.o frexpl.o fstat.o fstatat.o futimens.o getcwd-lgpl.o group-member.o localtime-buffer.o lstat.o mempcpy.o memrchr.o openat-proc.o printf-args.o printf-parse.o rename.o renameat.o vasnprintf.o vasprintf.o
gl_LTLIBOBJS =  asnprintf.lo asprintf.lo chdir-long.lo error.lo euidaccess.lo frexpl.lo fstat.lo fstatat.lo futimens.lo getcwd-lgpl.lo group-member.lo localtime-buffer.lo lstat.lo mempcpy.lo memrchr.lo openat-proc.lo printf-args.lo printf-parse.lo rename.lo renameat.lo vasnprintf.lo vasprintf.lo
gltests_LIBOBJS = 
gltests_LTLIBOBJS = 
gltests_WITNESS = IN_PORTAGE_UTILS_GNULIB_TESTS
host = x86_64-pc-solaris2.11
host_alias = 
host_cpu = x86_64
host_os = solaris2.11
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /net/ptah/export/gentoo/working-repos/portage-utils/autotools/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = -I autotools/m4
SUBDIRS = autotools/gnulib
portagedir = $(sysconfdir)/portage
postsyncddir = $(portagedir)/repo.postsync.d
dist_postsyncd_SCRIPTS = repo.postsync/q-reinit
q_SOURCES = main.c

# @@@ GEN START @@@ #
q_CPPFLAGS = -I$(top_builddir)/autotools/gnulib \
	-I$(top_srcdir)/autotools/gnulib -DAPPLET_q -DAPPLET_qatom \
	-DAPPLET_qcache -DAPPLET_qcheck -DAPPLET_qdepends \
	-DAPPLET_qfile -DAPPLET_qgrep -DAPPLET_qlist -DAPPLET_qlop \
	-DAPPLET_qmerge -DAPPLET_qpkg -DAPPLET_qsearch -DAPPLET_qsize \
	-DAPPLET_qtbz2 -DAPPLET_quse -DAPPLET_qxpak
q_LDADD = \
	$(top_builddir)/autotools/gnulib/libgnu.a \
	-liniparser \
	$(LIB_CLOCK_GETTIME) \
	$(LIB_EACCESS)

TMAKE = \
	$(MAKE) -C $(abs_top_srcdir)/tests \
		AUTOTOOLS=true \
		abs_top_builddir="$(abs_top_builddir)" \
		abs_top_srcdir="$(abs_top_srcdir)"


# Start off with base values which we append below
dist_man_MANS = man/q.1 man/qatom.1 man/qcache.1 man/qcheck.1 \
	man/qdepends.1 man/qfile.1 man/qgrep.1 man/qlist.1 man/qlop.1 \
	man/qmerge.1 man/qpkg.1 man/qsearch.1 man/qsize.1 man/qtbz2.1 \
	man/quse.1 man/qxpak.1
APPLETS = q qatom qcache qcheck qdepends qfile qgrep qlist qlop qmerge \
	qpkg qsearch qsize qtbz2 quse qxpak
EXTRA_DIST = autotools/m4/gnulib-cache.m4 applets.h config.h \
	include_applets.h libq/atom_compare.c libq/atom_explode.c \
	libq/basename.c libq/busybox.h libq/colors.c libq/compat.c \
	libq/copy_file.c libq/hash_fd.c libq/human_readable.c \
	libq/i18n.h libq/libq.c libq/libq.h libq/md5_sha1_sum.c \
	libq/prelink.c libq/profile.c libq/rmspace.c libq/safe_io.c \
	libq/scandirat.c libq/vdb.c libq/vdb_get_next_dir.c \
	libq/virtuals.c libq/xarray.c libq/xasprintf.c libq/xchdir.c \
	libq/xmalloc.c libq/xmkdir.c libq/xregex.c libq/xstrdup.c \
	libq/xsystem.c main.c main.h porting.h q.c qatom.c qcache.c \
	qcheck.c qdepends.c qfile.c qglsa.c qgrep.c qlist.c qlop.c \
	qmerge.c qpkg.c qsearch.c qsize.c qtbz2.c quse.c qxpak.c \
	tests/Makefile tests/atom_compare/.gitignore \
	tests/atom_compare/Makefile tests/atom_compare/atom-compare.py \
	tests/atom_compare/static.good \
	tests/atom_compare/static.q.good \
	tests/atom_compare/static.q.tests \
	tests/atom_compare/static.tests tests/atom_explode/.gitignore \
	tests/atom_explode/Makefile tests/atom_explode/atom-explode.py \
	tests/atom_explode/basic.good tests/atom_explode/basic.tests \
	tests/atom_explode/dotest tests/atom_explode/test.c \
	tests/copy_file/.gitignore tests/copy_file/Makefile \
	tests/copy_file/dotest tests/copy_file/test.c tests/init.sh \
	tests/install/.gitignore tests/install/Makefile \
	tests/install/dotest tests/mkdir/.gitignore \
	tests/mkdir/Makefile tests/mkdir/dotest tests/mkdir/test.c \
	tests/profile/Makefile tests/profile/dotest \
	tests/profile/profile1/etc/parent.conf \
	tests/profile/profile1/etc/portage/make.conf \
	tests/profile/profile1/etc/portage/subdir/file.conf \
	tests/profile/profile1/etc/portage/this.level.conf \
	tests/qatom/Makefile tests/qatom/dotest tests/qcheck/Makefile \
	tests/qcheck/dotest tests/qcheck/list01.good \
	tests/qcheck/list02.good tests/qcheck/list03.good \
	tests/qcheck/list04.good tests/qcheck/list05.good \
	tests/qcheck/list06.good tests/qcheck/list07.good \
	tests/qcheck/list08.good tests/qcheck/list09.good \
	tests/qcheck/root/a-b/pkg-1.0/CONTENTS \
	tests/qcheck/root/a-b/pkg-1.0/SLOT \
	tests/qcheck/root/a-b/pkg-1.0/repository \
	tests/qcheck/root/bin/bad-md5 tests/qcheck/root/bin/bad-mtime \
	tests/qcheck/root/bin/bad-mtime-obj \
	tests/qcheck/root/bin/bad-sha1 tests/qcheck/root/bin/good-md5 \
	tests/qcheck/root/bin/good-sha1 \
	tests/qcheck/root/cat/pkg-1/CONTENTS \
	tests/qcheck/root/cat/pkg-1/SLOT \
	tests/qcheck/root/cat/pkg-1/repository tests/qdepends/Makefile \
	tests/qdepends/dotest tests/qdepends/list01.good \
	tests/qdepends/list02.good tests/qdepends/list03.good \
	tests/qdepends/list04.good tests/qdepends/list05.good \
	tests/qdepends/list06.good tests/qdepends/list07.good \
	tests/qdepends/list08.good \
	tests/qdepends/root/app-arch/cpio-2.11/CONTENTS \
	tests/qdepends/root/app-arch/cpio-2.11/SLOT \
	tests/qdepends/root/app-arch/cpio-2.11/repository \
	tests/qdepends/root/x11-apps/xdm-1.1.11-r3/DEPEND \
	tests/qdepends/root/x11-apps/xdm-1.1.11-r3/RDEPEND \
	tests/qdepends/root/x11-apps/xdm-1.1.11-r3/USE \
	tests/qfile/Makefile tests/qfile/dotest tests/qlist/Makefile \
	tests/qlist/dotest tests/qlist/list01.good \
	tests/qlist/list02.good tests/qlist/list03.good \
	tests/qlist/list04.good tests/qlist/list05.good \
	tests/qlist/list06.good tests/qlist/list07.good \
	tests/qlist/list08.good tests/qlist/list09.good \
	tests/qlist/list10.good tests/qlist/list11.good \
	tests/qlist/list12.good tests/qlist/list13.good \
	tests/qlist/list14.good tests/qlist/list15.good \
	tests/qlist/list16.good tests/qlist/root/-merge-foo/CONTENTS \
	tests/qlist/root/a-b/a-0/CONTENTS \
	tests/qlist/root/a-b/a-0/SLOT \
	tests/qlist/root/a-b/a-0/repository \
	tests/qlist/root/a-b/b-0/CONTENTS \
	tests/qlist/root/a-b/b-0/SLOT \
	tests/qlist/root/a-b/b-0/repository \
	tests/qlist/root/app-arch/cpio-2.11/CONTENTS \
	tests/qlist/root/app-arch/cpio-2.11/SLOT \
	tests/qlist/root/app-arch/cpio-2.11/repository \
	tests/qlist/root/cat/pkg-1/CONTENTS \
	tests/qlist/root/cat/pkg-1/SLOT \
	tests/qlist/root/cat/pkg-1/repository \
	tests/qlist/root/cat/sub-2/CONTENTS \
	tests/qlist/root/cat/sub-2/SLOT \
	tests/qlist/root/cat/sub-2/repository \
	tests/qlist/root/sys-fs/mtools-4.0.13/CONTENTS \
	tests/qlist/root/sys-fs/mtools-4.0.13/SLOT \
	tests/qlist/root/sys-fs/mtools-4.0.13/repository \
	tests/qlop/Makefile tests/qlop/dotest tests/qlop/list01.good \
	tests/qlop/list02.good tests/qlop/list03.good \
	tests/qlop/list04.good tests/qlop/list05.good \
	tests/qlop/list06.good tests/qlop/list07.good \
	tests/qlop/list08.good tests/qlop/sync.log \
	tests/qlop/test04.good tests/qmerge/Makefile \
	tests/qmerge/dotest tests/qmerge/packages/Packages \
	tests/qmerge/packages/sys-devel/qmerge-test-1.3.tbz2 \
	tests/qtbz2/Makefile tests/qtbz2/dotest tests/quse/Makefile \
	tests/quse/dotest tests/quse/list01.good \
	tests/quse/portdir/profiles/arch.list \
	tests/quse/portdir/profiles/desc/elibc.desc \
	tests/quse/portdir/profiles/desc/one.desc \
	tests/quse/portdir/profiles/desc/two.desc \
	tests/quse/portdir/profiles/use.desc \
	tests/quse/portdir/profiles/use.local.desc \
	tests/qxpak/Makefile tests/qxpak/dotest \
	tests/qxpak/list01.good tests/qxpak/list02.good \
	tests/reinitialize/Makefile tests/reinitialize/dotest \
	tests/rmspace/.gitignore tests/rmspace/Makefile \
	tests/rmspace/dotest tests/rmspace/test.c \
	tests/source/Makefile tests/source/dotest tests/source/space \
	tests/subdir.mk tests/tests.h
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

q$(EXEEXT): $(q_OBJECTS) $(q_DEPENDENCIES) $(EXTRA_q_DEPENDENCIES) 
	@rm -f q$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(q_OBJECTS) $(q_LDADD) $(LIBS)
install-dist_postsyncdSCRIPTS: $(dist_postsyncd_SCRIPTS)
	@$(NORMAL_INSTALL)
	@list='$(dist_postsyncd_SCRIPTS)'; test -n "$(postsyncddir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(postsyncddir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(postsyncddir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  if test -f "$$d$$p"; then echo "$$d$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n' \
	    -e 'h;s|.*|.|' \
	    -e 'p;x;s,.*/,,;$(transform)' | sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1; } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) { files[d] = files[d] " " $$1; \
	      if (++n[d] == $(am__install_max)) { \
		print "f", d, files[d]; n[d] = 0; files[d] = "" } } \
	    else { print "f", d "/" $$4, $$1 } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	     if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	     test -z "$$files" || { \
	       echo " $(INSTALL_SCRIPT) $$files '$(DESTDIR)$(postsyncddir)$$dir'"; \
	       $(INSTALL_SCRIPT) $$files "$(DESTDIR)$(postsyncddir)$$dir" || exit $$?; \
	     } \
	; done

uninstall-dist_postsyncdSCRIPTS:
	@$(NORMAL_UNINSTALL)
	@list='$(dist_postsyncd_SCRIPTS)'; test -n "$(postsyncddir)" || exit 0; \
	files=`for p in $$list; do echo "$$p"; done | \
	       sed -e 's,.*/,,;$(transform)'`; \
	dir='$(DESTDIR)$(postsyncddir)'; $(am__uninstall_files_from_dir)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/q-main.Po

.c.o:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

q-main.o: main.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(q_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT q-main.o -MD -MP -MF $(DEPDIR)/q-main.Tpo -c -o q-main.o `test -f 'main.c' || echo '$(srcdir)/'`main.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/q-main.Tpo $(DEPDIR)/q-main.Po
#	$(AM_V_CC)source='main.c' object='q-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(q_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o q-main.o `test -f 'main.c' || echo '$(srcdir)/'`main.c

q-main.obj: main.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(q_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT q-main.obj -MD -MP -MF $(DEPDIR)/q-main.Tpo -c -o q-main.obj `if test -f 'main.c'; then $(CYGPATH_W) 'main.c'; else $(CYGPATH_W) '$(srcdir)/main.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/q-main.Tpo $(DEPDIR)/q-main.Po
#	$(AM_V_CC)source='main.c' object='q-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(q_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o q-main.obj `if test -f 'main.c'; then $(CYGPATH_W) 'main.c'; else $(CYGPATH_W) '$(srcdir)/main.c'; fi`
install-man1: $(dist_man_MANS)
	@$(NORMAL_INSTALL)
	@list1=''; \
	list2='$(dist_man_MANS)'; \
	test -n "$(man1dir)" \
	  && test -n "`echo $$list1$$list2`" \
	  || exit 0; \
	echo " $(MKDIR_P) '$(DESTDIR)$(man1dir)'"; \
	$(MKDIR_P) "$(DESTDIR)$(man1dir)" || exit 1; \
	{ for i in $$list1; do echo "$$i"; done;  \
	if test -n "$$list2"; then \
	  for i in $$list2; do echo "$$i"; done \
	    | sed -n '/\.1[a-z]*$$/p'; \
	fi; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
	done; }

uninstall-man1:
	@$(NORMAL_UNINSTALL)
	@list=''; test -n "$(man1dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	l2='$(dist_man_MANS)'; for i in $$l2; do echo "$$i"; done | \
	  sed -n '/\.1[a-z]*$$/p'; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	dir='$(DESTDIR)$(man1dir)'; $(am__uninstall_files_from_dir)

# This directory's subdirectories are mostly independent; you can cd
# into them and run 'make' without going through this Makefile.
# To change the values of 'make' variables: instead of editing Makefiles,
# (1) if the variable is set in 'config.status', edit 'config.status'
#     (which will cause the Makefiles to be regenerated when you run 'make');
# (2) otherwise, pass the desired values on the 'make' command line.
$(am__recursive_targets):
	@fail=; \
	if $(am__make_keepgoing); then \
	  failcom='fail=yes'; \
	else \
	  failcom='exit 1'; \
	fi; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-recursive
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-recursive

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-recursive

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    $(am__make_dryrun) \
	      || test -d "$(distdir)/$$subdir" \
	      || $(MKDIR_P) "$(distdir)/$$subdir" \
	      || exit 1; \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)
dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(PROGRAMS) $(SCRIPTS) $(MANS) config.h
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(postsyncddir)" "$(DESTDIR)$(man1dir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic clean-local mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am: install-dist_postsyncdSCRIPTS install-man

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-binPROGRAMS
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-exec-hook
install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man: install-man1

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-dist_postsyncdSCRIPTS \
	uninstall-man

uninstall-man: uninstall-man1

.MAKE: $(am__recursive_targets) all install-am install-exec-am \
	install-strip

.PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am \
	am--refresh check check-am clean clean-binPROGRAMS \
	clean-cscope clean-generic clean-local cscope cscopelist-am \
	ctags ctags-am dist dist-all dist-bzip2 dist-gzip dist-lzip \
	dist-shar dist-tarZ dist-xz dist-zip distcheck distclean \
	distclean-compile distclean-generic distclean-hdr \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am \
	install-dist_postsyncdSCRIPTS install-dvi install-dvi-am \
	install-exec install-exec-am install-exec-hook install-html \
	install-html-am install-info install-info-am install-man \
	install-man1 install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs installdirs-am maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS \
	uninstall-dist_postsyncdSCRIPTS uninstall-man uninstall-man1

.PRECIOUS: Makefile


install-exec-hook:
	cd $(DESTDIR)$(bindir); \
	for applet in $(APPLETS) ; do \
		[ ! -e "$$applet" ] && ln -s q $${applet} ; \
	done
check-hook:
	$(TMAKE) check
clean-local:
	$(TMAKE) clean
	-rmdir tests/*/ tests/
	rm -f $(APPLETS)
check: check-hook
# @@@ GEN START @@@ #

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
