#!/bin/bash

set -e

export PORTDIR=$PWD/portdir

rm -rf tmp
mkdir tmp
cd tmp

d=${PORTDIR}/profiles
entries() {
	sed -e 's:#.*::' -e '/^$/d' "$1"
}

# check arch.list
all=$(entries "$d/arch.list")
for x in ${all} ; do
	quse -CD $x > x
	echo " arch:$x: $x architecture" > good
	cat good >> all.good
	cmp x good
done
quse -CD ${all} > x
cmp x all.good
rm x good all.good

# check use.desc
all=$(entries "$d/use.desc" | awk '{print $1}')
for x in ${all} ; do
	quse -CD
done

###### faster test needed.########
exit 0
##################################
type -p mksquashfs || exit 0

export PORTDIR=$(portageq envvar PORTDIR) ;

arches="x86 amd64 ppc"

for arch in $arches; do
	mkdir -p PORTDIR-${arch}
	cd PORTDIR-${arch} || exit 1
	[[ ! -e arch.${arch} ]] && quse -CKe ${arch} > arch.${arch} ;
	awk '{print $1}' < arch.${arch} | cut -d / -f 1-2 | uniq | while read cpn ; do mkdir -p $cpn ; done ; 
	for ebuild in $(awk '{print $1}' < arch.${arch}) ; do cp $PORTDIR/$ebuild ./$ebuild; done ;
	quse -CKe ${arch} | awk '{print $1}' | cut -d / -f 1-2 | uniq | while read cpn ; do cp -a $PORTDIR/$cpn/files ./$cpn/; done ;
	cp -a $PORTDIR/{eclass,profiles,licences} . ; sync ; 
	find . -type d -name CVS | while read foo; do rm $foo/* ; sync ; rmdir $foo ; done ;
	mksquashfs ./ ../PORTDIR-${arch}.squashfs -noappend -e arch.${arch} ; 
	rm -rf *-*
	cd -
done
ls -lh PORTDIR-*.squashfs
